Fixed federator error on creating of a new transaction
rsksmart/tokenbridge pull request #327
Opened 2022-03-09 20:22 UTC by coolwather

2022-03-09 20:59 UTC, pmprete requested changes
There is an underlying error, instead of returning null we should fix the actual error

2022-03-09 20:59 UTC, pmprete commented on federator/src/lib/FederatorERC.ts
> +        if (!receipt.status) {
i would join both conditions into one if

2022-03-09 20:59 UTC, pmprete commented on federator/src/lib/TransactionSender.ts
> +      return null;
This looks dangerous,  as there is an actual error here and it's being swallowed

2022-03-09 20:59 UTC, pmprete commented on federator/src/lib/TransactionSender.ts
> +      return null;
Instead of asking for null gas we should fix the error that is being caused on calculating the gas

2022-03-09 20:59 UTC, pmprete commented on federator/src/lib/TransactionSender.ts
> +      if (rawTx === null) {
Why rawTx is null?

2022-03-10 15:57 UTC, coolwather commented
I removed all my previously changes in the PR, and added a validation to process the transaction vote and so on only if the transaction it's for that federator side chain.

2022-03-11 20:57 UTC, pmprete approved these changes
Good work!

2022-03-11 20:57 UTC, merged