GBI-543 - Federator: Remove all code related to NFT support
rsksmart/tokenbridge pull request #336
Opened 2022-04-28 19:35 UTC by joaoiovlabs

### Federator: Remove all code related to NFT support

### Description

- It was removed TokenType (unused parameter)
-  It was removed all references of NFT

2022-04-28 19:41 UTC, coolwather commented
Looks good to me, just take a look on the code smells.

2022-04-29 12:35 UTC, coolwather commented
There is an error on the build.

2022-04-29 12:58 UTC, aguschirico requested changes
Please review failing tests.

2022-05-02 10:27 UTC, aguschirico approved these changes

2022-05-04 14:28 UTC, aguschirico approved these changes

2022-05-04 14:29 UTC, merged